## Numpy

Numpy is a Fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [1]:
import numpy as np

### Creating Array

In [ ]:
## 1-D Array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))            #ndarray ---> n dimentional array
print(arr1.shape)            # It gives the shape of the array.

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [17]:
## 2-D Array
arr2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr2)
print(arr2.shape)            ## 2 rows and 3 columns

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [16]:
## 3-D Array
arr3 = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr3)
print(arr3.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [19]:
## Creating arrays using inbuilt functions.
# 1.) arange(start,stop,step)
arr = np.arange(0,10,2).reshape(5,1)
print(arr)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [22]:
# 2.) ones(rows, columns)
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# 3.) zeros(rows, columns)
arr = np.zeros((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
# 4.) eye(order of matrix)
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of Numpy
arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape:\n", arr.shape)
print("Number of Dimensions:",  arr.ndim)
print("Size (number of elements):", arr.size)
print("Data Type:", arr.dtype)
print("Item Size (in bytes) :", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
Number of Dimensions: 2
Size (number of elements): 6
Data Type: int64
Item Size (in bytes) : 8


In [27]:
## Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print("Addition: ", arr1 + arr2)

## Element wise Subtraction
print("Subtraction :", arr2 - arr1)

## Element wise Multiplication
print("Multiplication :", arr1 * arr2)

## Element wise Division
print("Division: ", arr2 / arr1)

Addition:  [11 22 33 44 55]
Subtraction : [ 9 18 27 36 45]
Multiplication : [ 10  40  90 160 250]
Division:  [10. 10. 10. 10. 10.]


In [ ]:
## Universal Functions
arr = np.array([2,3,4,5,6])

## Square Root
print('Square Root: ', np.sqrt(arr))

## Exponential
print("Exponential: ", np.exp(arr))

## Sine
print("Sine: ", np.sin(arr))

## Natural Log
print("Log: ", np.log(arr))

Square Root:  [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential:  [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine:  [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Log:  [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [37]:
## Array Slicing and Indexing
arr = np.arange(1,13).reshape(3,4)     ## Two Dimentional Array
print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr[0][0]          ## 1st element in the 1st row

np.int64(1)

In [ ]:
arr[1:,2:]            ## Last two elements from both the rows

array([[ 7,  8],
       [11, 12]])

In [42]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [44]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [45]:
## Modify array Elements
arr[0,0] = 100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [46]:
arr[1:] = 100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [47]:
## Statistical Concept  -- Normalization
# ---> To have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
stv_dev = np.std(data)

## Normalize the data
normalized_data = (data - mean) / stv_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [48]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean: ", mean)

# Median
median = np.median(data)
print("Median: ", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

# Variance
variance = np.var(data)
print("Variance: ", variance)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [53]:
## Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data > 5) & (data < 8)]

array([6, 7])