In [2]:
import numpy as np

### 1. What is NumPy and why is it used in Python?

In [1]:
## NumPy (Numerical Python) is a powerful Python library used for fast numerical computation, especially with large datasets.
# NumPy helps Python handle mathematics and data operations efficiently, making it the backbone of data science.

### 2. How do you install NumPy in Python?

In [2]:
# !pip install numpy

### 3. How do you create a 1D NumPy array from a Python list?

In [4]:
a = [1,2,3,4,5,6,7,8,9]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 4. How do you create a 2D NumPy array?

In [7]:
arr2d = np.array([[1,2], [4,5]])
print("Array:\n", arr2d)
print("-------")
print("Dimension:", arr2d.ndim)

Array:
 [[1 2]
 [4 5]]
-------
Dimension: 2


### 5. How do you check the size, shape, and data type of a NumPy array?

In [ ]:
a = [1,2,3,4,5,6,7,8,9]
arr = np.array(a)

print("Size:\n", arr.size)
print("Shape:\n", arr.shape)
print("Data Type:\n", arr.dtype)

Size:
 9
Shape:
 (9,)
Data Type:
 int64


### 6. How do you generate an array filled with zeros of shape (3, 4)?

In [9]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 7. How do you generate an array filled with ones of shape (2, 5)?

In [10]:
arr = np.ones((2,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 8. What is the difference between np.arange() and np.linspace()?

In [19]:
# arange ---> It creates an array in a given range(start, stop, step)
# linspace ---> It creates an array in a given range but with equal spacing between them

arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.linspace(3,27,9).reshape(3,3)

print("Array of arange:", arr1)
print()
print("Array of linspace:\n", arr2)

Array of arange: [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array of linspace:
 [[ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]]


### 9. How do you create an identity matrix of size 4×4?

In [21]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 10. How do you create a random array of shape (3, 3) with values between 0 and 1?

In [22]:
arr = np.random.rand(3,3)
arr

array([[0.6968591 , 0.80319732, 0.51576461],
       [0.59289916, 0.90942994, 0.071107  ],
       [0.44418097, 0.67655803, 0.19530388]])

### 11. How do you access the first element of a NumPy array?

In [3]:
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

1
2
3
4
5


### 12. How do you slice the first 3 rows and 2 columns from a 2D array?

In [ ]:
# arr[row_index, column_index]

In [ ]:
np.random.seed(2)
arr = np.random.randint(1,20,18).reshape(6,3)
print(arr)
# arr[0:3, 0:2]

print(arr[[0,1], [1,2]])    #Fancy Slicing

[[ 9 16 14]
 [ 9 12 19]
 [12  9  8]
 [ 3 18 12]
 [16  6  8]
 [ 4  7  5]]
[16 19]


### 13. What is the difference between basic slicing and fancy indexing?

### 14. How do you reverse a NumPy array?

In [29]:
arr = np.arange(1,10).reshape(3,3)
reversed_arr = arr[::-1]   ##Using Slicing
print(reversed_arr,"\n")

rev1 = np.fliplr(arr)    # Horizontal Flipping
print(rev1, "\n")
rev2 = np.flipud(arr)
print(rev2)

[[7 8 9]
 [4 5 6]
 [1 2 3]] 

[[3 2 1]
 [6 5 4]
 [9 8 7]] 

[[7 8 9]
 [4 5 6]
 [1 2 3]]


### 15. How do you add, subtract, multiply, and divide two NumPy arrays?

In [33]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(10,19).reshape(3,3)
print("Array 1:\n", a1)
print("Array 2:\n", a2)
addition = a1 + a2
print("Addition:\n", addition)
subtraction = a2 - a1
print("Subtraction:\n", subtraction)
multiplication1 = a1 * a2
print("Scaler Multiplication:\n", multiplication1)
multiplication2 = a1.dot(a2)
print("Matrix Multiplication:\n", multiplication2)

Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Addition:
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
Subtraction:
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
Scaler Multiplication:
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
Matrix Multiplication:
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


### 16. What is broadcasting in NumPy?

In [34]:
a = np.array([1, 2, 3])
a + 10

array([11, 12, 13])

### 17. How do you calculate the mean, median, and standard deviation of an array?

In [37]:
np.random.seed(11)
arr = np.random.randint(1,100,9).reshape(3,3)
mean = np.mean(arr)
std = np.std(arr)
median = np.median(arr)

print("Mean : ", mean)
print()
print("Standard Deviation : ", std)
print()
print("Median : ", median)

Mean :  58.44444444444444

Standard Deviation :  26.238695390633833

Median :  64.0


### 18. How do you find the minimum and maximum values of an array?

In [40]:
np.random.seed(12)
arr = np.random.randint(1,100,9).reshape(3,3)
print("Array:\n ", arr)
maximum = np.max(arr)
minimum = np.min(arr)
print("Maximum Number: ", maximum)
print("Minimum Number: ", minimum)

Array:
  [[76 28  7]
 [ 3  4 68]
 [77 49 23]]
Maximum Number:  77
Minimum Number:  3


### 19. How do you reshape a 1D array of size 12 into a 3×4 array?

In [41]:
np.random.seed(13)
arr = np.random.randint(1,100,12).reshape(3,4)
print(arr)

[[83 49 75 17]
 [99 26 59 27]
 [67 47 55 78]]


### 20. How do you flatten a 2D array into a 1D array?

In [55]:
arr2d = np.arange(1,7).reshape(2,3)
arr = arr2d.flatten()
arr

array([1, 2, 3, 4, 5, 6])

### 21. How do you filter elements from an array that are greater than 10?

In [58]:
np.random.seed(15)
arr = np.random.randint(1,100,9).reshape(3,3)
print('Array:\n', arr)
new = arr[arr > 10]
print("Filtered Array:\n", new)

Array:
 [[73 13  6]
 [ 1 29 28]
 [72 76 86]]
Filtered Array:
 [73 13 29 28 72 76 86]


### 22. How do you replace all negative values in an array with zero?

In [ ]:
arr = np.array([-1,2,-3,4,-5,6,-7,8,-9], ndmin=2).reshape(3,3)
arr[arr < 0] = 0
arr

array([[0, 2, 0],
       [4, 0, 6],
       [0, 8, 0]])

### 23. How do you find the indices of all elements equal to a specific value?

In [ ]:
a = np.array([10, 20, 30, 20, 40, 20])

indices = np.where(a == 20)
print(indices)

indices = np.where(a == 20)[0]

(array([1, 3, 5]),)
[1 3 5]


In [64]:
indices = np.nonzero(a == 20)
print(indices)

(array([1, 3, 5]),)


In [ ]:
b = np.array([[1, 2, 3],
              [4, 2, 6],
              [7, 8, 2]])

rows, cols = np.where(b == 2)

print(rows)
print(cols)

[0 1 2]
[1 1 2]


In [ ]:
## 3d Array
arr = np.array([1,2,2,3,4,3,4,3,4], ndmin=3).reshape(3,3)
print(arr)
# arr[depth_index, row_index, col_index]
indices = np.where(arr == 3)
indices

[[1 2 2]
 [3 4 3]
 [4 3 4]]


(array([1, 1, 2]), array([0, 2, 1]))

### 24. How do you extract only even numbers from a NumPy array?

In [72]:
np.random.seed(14)
arr = np.random.randint(1,100,9).reshape(3,3)
print(arr)
even = arr[arr % 2 == 0]
print(even)

[[89 13 23]
 [72 29 11]
 [81 62 27]]
[72 62]


### 25. What is np.where() and how is it used?

In [ ]:
# np.where() is a NumPy function used to return the indices of elements that satisfy a given condition. 
# It works with boolean expressions and is commonly used for filtering, locating values, and conditional replacement.
# It returns a tuple of arrays (one for each dimension) representing the positions where the condition is True.

### 26. How do you horizontally stack two arrays?

In [73]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

arr = np.hstack((a1,a2))
arr

array([1, 2, 3, 4, 5, 6])

### 27. How do you vertically stack two arrays?

In [74]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

arr = np.vstack((a1,a2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

### 28. How do you split an array into 3 equal parts?

In [ ]:
arr = np.arange(1, 10).reshape(3, 3)
new = np.hsplit(arr, 3)

print(new)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


### 29. How do you concatenate multiple arrays in NumPy?

In [ ]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])
c = np.array([[5, 6]])

result = np.concatenate((a, b, c), axis=0)     ## Axis = 1 ---> Row wise
print(result)      ## Column wise operation

[[1 2]
 [3 4]
 [5 6]]


### 30. How do you perform matrix multiplication using NumPy?

In [80]:
np.random.seed(16)
a1 = np.random.randint(1,100,9).reshape(3,3)
np.random.seed(17)
a2 = np.random.randint(1,100,9).reshape(3,3)

multiple = a1.dot(a2)
print("Matrix Multiplication :\n", multiple)

Matrix Multiplication :
 [[6844 8068 5216]
 [3120 2300 2523]
 [6842 5929 3877]]


### 31. What’s the difference between * and np.dot()?

In [11]:
#Use of '*'
arr1 = np.ones((3,3))
print()
print(arr * 3)   # All the elemenst are multiplied by 3

arr2 = np.random.randint(1,100,9).reshape(3,3)
print(arr2)

multiple = arr1.dot(arr2)
print(multiple)


[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[31 36 76]
 [31 51 70]
 [56 18 91]]
[[118. 105. 237.]
 [118. 105. 237.]
 [118. 105. 237.]]


### 32. How do you compute the determinant of a matrix?

In [ ]:
# Matrix
A = np.random.randint(1,100,9).reshape(3,3)
print(A)
det = np.linalg.det(A)        # Determinant

print("Determinant:\n", det)

[[61 62 67]
 [72 60 93]
 [16 50 83]]
Determinant:
 -81246.00000000007


### 33. How do you compute the inverse of a matrix?

In [ ]:
arr = np.array([[4, 7],
              [2, 6]])

inverse_arr = np.linalg.inv(arr)
print("Inverse of A:\n", inverse_arr)

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


### 34. How do you calculate eigenvalues and eigenvectors?

In [24]:
arr = np.random.randint(100,200,9).reshape(3,3)
eig_vals, eig_vecs = np.linalg.eig(A)        # Eigenvalues and Eigenvectors

print("Eigenvalue:\n", eig_vals)
print("Eigenvector:\n", eig_vecs)

Eigenvalue:
 [182.25723303  34.61929973 -12.87653276]
Eigenvector:
 [[-0.5890725  -0.67250411  0.36629949]
 [-0.67954799 -0.39213811 -0.8487058 ]
 [-0.43727352  0.62766705  0.38147498]]


### 35. How do you create a random integer array between 50 and 100 of size 10?

In [25]:
arr = np.random.randint(50,100,10)
print(arr)

[96 83 91 66 78 63 83 98 84 60]


### 36. How do you shuffle an array randomly?

In [29]:
arr = np.random.randint(1, 1000, 9).reshape(3, 3)
print("Array:\n", arr)

np.random.shuffle(arr)   
print("Shuffled Array:\n", arr)


Array:
 [[304 642 528]
 [518  18 197]
 [446 392 328]]
Shuffled Array:
 [[304 642 528]
 [446 392 328]
 [518  18 197]]


### 37. How do you set a random seed in NumPy for reproducibility?

In [30]:
np.random.seed(20)
arr = np.random.randint(1,100,9).reshape(3,3)
print(arr)

[[91 16 96]
 [29 91 10]
 [21 76 23]]


### 38. What is the difference between rand(), randn(), and randint()?

In [31]:
# Using rand(): Random floats between 0 and 1
rand_array = np.random.rand(2, 3)
print("rand():\n", rand_array)

# Using randn(): Random floats from standard normal distribution
randn_array = np.random.randn(2, 3)
print("\nrandn():\n", randn_array)

# Using randint(): Random integers within a specified range
randint_array = np.random.randint(10, 50, size=(2, 3))
print("\nrandint():\n", randint_array)


rand():
 [[0.69175758 0.37868094 0.51851095]
 [0.65795147 0.19385022 0.2723164 ]]

randn():
 [[ 0.91635593  0.70783847  0.41967613]
 [ 0.53415759 -0.81795944  0.78815866]]

randint():
 [[13 20 21]
 [23 29 40]]


### 39. How do you remove duplicate elements from a NumPy array?

In [34]:
## By using unique function
arr = np.array([1,2,2,3,3,3,4,4,4,4])
new = np.unique(arr).reshape(2,2)
print(new)

[[1 2]
 [3 4]]


### 40. How do you sort a NumPy array along a specific axis?

In [37]:
arr = np.random.randint(300,400, size= (3,3))
print("Array:\n", arr)
sorted_arr1 = np.sort(arr, axis = 0)
sorted_arr2 = np.sort(arr, axis = 1)
print("Column Wise Sorting:\n", sorted_arr1)
print("Row Wise Sorting:\n", sorted_arr2)

Array:
 [[316 318 379]
 [390 359 371]
 [375 329 345]]
Column Wise Sorting:
 [[316 318 345]
 [375 329 371]
 [390 359 379]]
Row Wise Sorting:
 [[316 318 379]
 [359 371 390]
 [329 345 375]]


### 41. Explain the broadcasting rules in NumPy with examples.

In [ ]:
A = np.array([[1,2,3],
              [4,5,6]])
b = np.array([10,20,30])
A + b



array([[11, 22, 33],
       [14, 25, 36]])

In [40]:
a = np.array([[1],
              [2],
              [3]])  # shape (3,1)

b = np.array([10, 20, 30])  # shape (3,)
a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

### 42. How do you vectorize a Python function using np.vectorize()?

In [41]:
# Normal Python function (works on single values)
def square_and_check(x):
    if x % 2 == 0:
        return x**2   # square even numbers
    else:
        return x**3   # cube odd numbers

# Vectorize the function
vec_func = np.vectorize(square_and_check)

# Apply on array
arr = np.array([1, 2, 3, 4, 5])
result = vec_func(arr)

print("Original Array:", arr)
print("Vectorized Output:", result)


Original Array: [1 2 3 4 5]
Vectorized Output: [  1   4  27  16 125]


### 43. What is the difference between vectorization and loops in terms of speed?

In [42]:
# Vectorization uses optimized C-based NumPy operations that run on entire arrays at once, making them significantly faster than 
# traditional Python loops, which process elements one-by-one. 
# Vectorized operations reduce Python-level overhead, improve memory access patterns, and take advantage of SIMD and low-level optimizations. 
# Therefore, vectorization is preferred for speed, efficiency, and cleaner code.